# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
 
PRODUCT_COPY_FILES += \
#	/vendor/samsung/j7ltespr/proprietary/etc/B05QL_s5k5e3yx_module_info.xml:system/etc/B05QL_s5k5e3yx_module_info.xml \
#	/vendor/samsung/j7ltespr/proprietary/etc/T13QL_s5k3l2xx_module_info.xml:system/etc/T13QL_s5k3l2xx_module_info.xml \
	/vendor/samsung/j7ltespr/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
	/vendor/samsung/j7ltespr/proprietary/app/mcRegistry/07050500000000000000000000000000.tlbin:system/app/mcRegistry/07050500000000000000000000000000.tlbin \
	/vendor/samsung/j7ltespr/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	/vendor/samsung/j7ltespr/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k3l2xx_vt_hd.so:system/vendor/lib/libchromatix_s5k3l2xx_vt_hd.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:system/vendor/lib/libmmcamera_s5k5e3yx.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k3l2xx_vt.so:system/vendor/lib/libchromatix_s5k3l2xx_vt.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_common.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_common.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_video.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_video.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_s5k3l2xx.so:system/vendor/lib/libmmcamera_s5k3l2xx.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libactuator_dw9806_camera.so:system/vendor/lib/libactuator_dw9806_camera.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libactuator_dw9806_camcorder.so:system/vendor/lib/libactuator_dw9806_camcorder.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so:system/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
	/vendor/samsung/j7ltespr/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
	/vendor/samsung/j7ltespr/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
	/vendor/samsung/j7ltespr/proprietary/lib/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmmcamera_cac2_lib_13M.so:system/lib/libmmcamera_cac2_lib_13M.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaf_algo_rear.so:system/lib/libaf_algo_rear.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
#	/vendor/samsung/j7ltespr/proprietary/lib/libcommon_time_client.so:system/lib/libcommon_time_client.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SA_GoogleFX_ver119k.so:system/lib/lib_SA_GoogleFX_ver119k.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libAl_Awb.so:system/lib/libAl_Awb.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaec_algo_rear.so:system/lib/libaec_algo_rear.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsamsungvad.so:system/lib/libsamsungvad.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SoundAlive_play_plus_ver126a.so:system/lib/lib_SoundAlive_play_plus_ver126a.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmysound.so:system/lib/libmysound.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsamsungVoipResampler.so:system/lib/libsamsungVoipResampler.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libril.so:system/lib/libril.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_DNSe_EP_ver216c.so:system/lib/lib_DNSe_EP_ver216c.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libjpega.so:system/lib/libjpega.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SamsungVAD_v01009.so:system/lib/lib_SamsungVAD_v01009.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libatparser.so:system/lib/libatparser.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaec_algo_front.so:system/lib/libaec_algo_front.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libAl_Awb_Sp.so:system/lib/libAl_Awb_Sp.so \
	/vendor/samsung/j7ltespr/proprietary/lib/liblbs_core.so:system/lib/liblbs_core.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libcordon.so:system/lib/libcordon.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
	/vendor/samsung/j7ltespr/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libawb_algo_front_al.so:system/lib/libawb_algo_front_al.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
	/vendor/samsung/j7ltespr/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libizat_core.so:system/lib/libizat_core.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libmmcamera2_stats_algorithm.so:system/lib/libmmcamera2_stats_algorithm.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
	/vendor/samsung/j7ltespr/proprietary/lib/libawb_algo_rear_al.so:system/lib/libawb_algo_rear_al.so \
	/vendor/samsung/j7ltespr/proprietary/lib/hw/audio.primary.msm8916.so:system/lib/hw/audio.primary.msm8916.so \
	/vendor/samsung/j7ltespr/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
	/vendor/samsung/j7ltespr/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
	/vendor/samsung/j7ltespr/proprietary/lib/soundfx/libaudiosa_sec.so:system/lib/soundfx/libaudiosa_sec.so \
	/vendor/samsung/j7ltespr/proprietary/lib/soundfx/libaudioeffectoffload.so:system/lib/soundfx/libaudioeffectoffload.so \
#	/vendor/samsung/j7ltespr/proprietary/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
	/vendor/samsung/j7ltespr/proprietary/bin/radish:system/bin/radish \
	/vendor/samsung/j7ltespr/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	/vendor/samsung/j7ltespr/proprietary/bin/irsc_util:system/bin/irsc_util \
	/vendor/samsung/j7ltespr/proprietary/bin/ssr_setup:system/bin/ssr_setup \
	/vendor/samsung/j7ltespr/proprietary/bin/rild:system/bin/rild \
	/vendor/samsung/j7ltespr/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	/vendor/samsung/j7ltespr/proprietary/bin/netmgrd:system/bin/netmgrd \
	/vendor/samsung/j7ltespr/proprietary/bin/loc_launcher:system/bin/loc_launcher \
	/vendor/samsung/j7ltespr/proprietary/bin/adsprpcd:system/bin/adsprpcd \
	/vendor/samsung/j7ltespr/proprietary/bin/time_daemon:system/bin/time_daemon \
	/vendor/samsung/j7ltespr/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	/vendor/samsung/j7ltespr/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
	/vendor/samsung/j7ltespr/proprietary/bin/qseecomd:system/bin/qseecomd \
	/vendor/samsung/j7ltespr/proprietary/bin/qmuxd:system/bin/qmuxd \
	/vendor/samsung/j7ltespr/proprietary/bin/ssr_diag:system/bin/ssr_diag \
	/vendor/samsung/j7ltespr/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
	/vendor/samsung/j7ltespr/proprietary/bin/btnvtool:system/bin/btnvtool \
	/vendor/samsung/j7ltespr/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
	/vendor/samsung/j7ltespr/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
